### ISSUE TITLE
Error Whenever Trying To Export To Laser

### ISSUE THREAD

**Issue by schradieck** [photodude/BIBO2-LaserPlugin#1]
every time i either click preview, or apply in the export window i get this message, and no output:
Tested on version 1.01 & 1.02, both with fresh installs

Traceback (most recent call last):
  File "laser.py", line 1459, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "laser.py", line 1437, in effect
    self.orientation(self.layers[min(0, len(self.layers) - 1)])
  File "laser.py", line 1377, in orientation
    points = points[:2]
UnboundLocalError: local variable 'points' referenced before assignment

**Comment by photodude** [comment]
@schradieck I've pushed a possible fix. Try the current branch. I'll push a few more changes soon.

**Comment by schradieck** [comment]
error is still present, the referenced lines in the error message have changed, but asides from that it's the same
tested on versions 1.01 and 1.02


Traceback (most recent call last):
  File "laser.py", line 1461, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "laser.py", line 1439, in effect
    self.orientation(self.layers[min(0, len(self.layers) - 1)])
  File "laser.py", line 1381, in orientation
    print_(("using orientation scale", orientation_scale, "i=", points))
UnboundLocalError: local variable 'orientation_scale' referenced before assignment

**Comment by photodude** [comment]
I'll have to take a look it's the same type of error but the error is on a different item as it's now on ```orientation_scale```

I'll try to take a look at it tomorrow afternoon.

**Comment by photodude** [comment]
@schradieck That is a very odd error. The line erroring is after a conditional which checks if the units are set in mm or in inches. the only way it should error is if your units in inkscape are not in mm or in inches (pixels, picas, etc). 

I've added a default value forcing the ```orientation_scale``` to mm to work around the error.

**Comment by schradieck** [comment]
Weird, as I always used mm, will test in a couple hours and let you know
how it goes!

**Comment by photodude** [comment]
@schradieck  It could be in the laser.inx parameters where the units are set. I'll see if I can force a default there as well.

**Comment by photodude** [comment]
@schradieck Did you get a chance to try the update?

**Comment by schradieck** [comment]
Sorry, I have not. Was away from home for the last week. Should be able to
tomorrow

**Comment by schradieck** [comment]
was able to test, and got this error:

"Orientation points for 'Layer 1' layer have not been found! Please add orientation points using Orientation tab!"

i found the settings for orientation points under the basic Gcode Tools extension, and added said points, and trying to export after that gave me this error:

Traceback (most recent call last):
  File "laser.py", line 1462, in <module>
    e.run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 140, in run
    self.save_raw(self.effect())
  File "laser.py", line 1435, in effect
    self.get_info()
  File "laser.py", line 1145, in get_info
    recursive_search(self.document.getroot(), self.document.getroot())
  File "laser.py", line 1119, in recursive_search
    recursive_search(i, i)
  File "laser.py", line 1121, in recursive_search
    points = self.get_orientation_points(i)
  File "laser.py", line 1169, in get_orientation_points
    r = re.match(
  File "C:\Program Files\Inkscape\lib\python3.8\re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
